[package]
name = "enclave-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { version="0.56.0", features=["tcp", "noise", "yamux", "relay", "tokio"] }
tokio = { version="1.49.0", features=["full"] }